#!/bin/sh
#
# Copyright (c) 2010 Torsten Rehn <torsten@rehn.tel>
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
#
#
# Make sure to set env.mysqlopts so that mysqlshow can run without
# requiring a password. On Ubuntu/Debian systems,
#	
#	[mysql_*]
#	user root
#	env.mysqlopts --defaults-extra-file=/etc/mysql/debian.cnf
#
# is usually a good idea. Then, include the name of the database(s)
# in your symlinks name:
#
#	cd /etc/munin/plugins
#	ln -s /usr/share/munin/plugins/mysql_rowcount_ mysql_rowcount_mydb1
#	ln -s /usr/share/munin/plugins/mysql_rowcount_ mysql_rowcount_mydb2
#
#%# family=auto
#%# capabilities=autoconf

MYSQLOPTS="$mysqlopts"
MYSQLSHOW="mysqlshow"
MYSQLDB=`basename $0 | sed 's/^mysql_rowcount_//g'`

if [ "$1" = "autoconf" ]; then
	$MYSQLSHOW $MYSQLOPTS --status $MYSQLDB 2>/dev/null >/dev/null
	if [ $? -eq 0 ]
	then   
		echo "yes"
		exit 0
	else   
		echo "no"
		exit 1
	fi
fi

if [ "$1" = "config" ]; then
	tables=$($MYSQLSHOW $MYSQLOPTS --status $MYSQLDB | cut -d "|" -f 2 | sed "s/^ //g" | grep -v "^Name" | grep -v "^Database: " | grep -v "^\+---")
	echo "graph_title Length of tables in MySQL database $MYSQLDB"
	echo "graph_vlabel number of rows"
	echo "graph_category mysql"
	for table in $tables; do
	echo "mysql_rows_$MYSQLDB_$table.label $table"
	done
	exit 0
fi

$MYSQLSHOW $MYSQLOPTS --status $MYSQLDB | cut -d "|" -f 2,6 | grep "[0-9]" | sed "s/^ //g" | sed "s/\s*| / /g" | sed "s/^/mysql_rows_$MYSQLDB_/" | awk '{gsub(/^ +| +$/,"")}1' | sed "s/ /.value /g"